#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi

case "$1" in
	start)
		echo -e "\e[00;31mEl proceso puede durar varias horas, por favor espere...\e[00m"
		mv -f /etc/memlockd.cfg /etc/memlockd.cfg.old
		mv -f /etc/memlockd.cfg.des /etc/memlockd.cfg
		systemctl start memlockd
		history -c
		umount -fl /tmp
		umount -fl /var/tmp
		umount -fl /var/log
		umount -fl /var/cache/samba
		umount -fl /var/spool
		if ! [[ -d /lib/live/mount/rootfs ]]; then
			for i in $(fdisk -l | grep "Disco" | sed '/zram/d' | sed '/loop/d' | awk '{print $2}' | sed 's/.$//g'); do
				dd if=/dev/zero | pv | dd of=$i bs=1024k count=1
				shred -vfz -n 5 $i
				dd if=/dev/urandom | pv | dd of=$i bs=4096
				dd if=/dev/zero | pv | dd of=$i iflag=nocache oflag=direct bs=4096
			done
		else
			for j in $(fdisk -l | grep "swap" | awk '{print $1}'); do
				sswap -fl $j
			done
		fi
		sdmem -fl
		poweroff
		;;

	*)
            	echo "USO: $(basename $0) {start}"
		;;

esac
exit 0
